#!/bin/sh
# Nos movemos a la raíz donde está el package.json de la app
cd /app/lib/jearcast/resources/app/

# Ejecutamos pasando la ruta relativa al main.js configurado en package.json
exec /app/lib/jearcast/jearcast --no-sandbox src/main.js "$@"